config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create]
  get '/logout', controller: 'sessions', action: 'destroy'

  resources :lists do
    resources :gifts
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
# frozen_string_literal: true

class Gift < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  belongs_to :user
  has_many :gifts
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  validates :username, uniqueness: true
  validates :email, uniqueness: { message: 'already registered' }

  def email=(value)
    value = value.strip.downcase
    self[:email] = value
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :find_list
  
  # def index
  #   @gifts = Gift.all
  # end

  def new
    @gift = Gift.new
  end

  def create
      @gift = @list.gifts.create(gift_params)
    if @gift.save
      redirect_to list_path(params[:list_id])
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @gift.update(gift_params)
      redirect_to list_path(params[:list_id])
    else
      render 'edit'
    end
  end

  def destroy
    @gift = @list.gifts.find(params[:id])
    @gift.destroy
    redirect_to list_path(params[:list_id])
  end

  private

  def gift_params
    params.require(:gift).permit(:name, :url, :image, :notes).merge(user_id: current_user.id)
  end

  def find_list
    @list = List.find_by(id: params[:list_id])
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  before_action :find_list, only: %i[edit update destroy show]

  def index
    @lists = List.all
  end

  def show
    @gift = Gift.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(user_id: session[:user_id], name: params[:list][:name], event_date: params[:list][:event_date],
                     archived: false)
    if @list.save
      redirect_to lists_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      redirect_to lists_url
    else
      render 'edit'
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url
  end

  private

  def find_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :event_date)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email].downcase)

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Signed in successfully'
      redirect_to lists_url
    else
      flash.now[:alert] = 'Invalid login details'
      render 'new'
    end
  end

  def destroy
    session.clear
    flash[:notice] = 'Successfully signed out'
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = 'Successfully signed up'
      redirect_to new_session_url
    else
      render 'new'
    end
  end

  def welcome
    @user = params[:username]
    render :welcome
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :password_confirmation,
      :birthdate
    )
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/gifts/_form.html.erb
<div class="card mx-auto text-center px-4 pt-4 pb-3 mt-5" style="width: 375px;">
  <%= form_for [@list, @gift], url: list_gifts_path(@list, @gift) do |f| %>
    <%= f.label :name, 'Gift name' %>
    <%= f.text_field :name, class: "form-control mb-3" %>
    <%= f.label :url, 'url' %>
    <%= f.text_field :url, class: "form-control mb-3" %>
    <%= f.label :notes, 'Notes' %>
    <%= f.text_field :notes, class: "form-control mb-3" %>
    <%= f.submit 'Add Gift', class: "btn btn-success" %>
  <% end %>
</div>

app/views/gifts/_index.html.erb
<% @list.gifts.reverse.each do |gift| %>
    <div class="card my-0.5 mx-auto" style="width: 98%;" id="gift-<%=gift.id%>">
      <span class="card-body">
        <h5 class="card-title"> <%= gift.name %></h5>
        <% if @list.user == current_user %>
        <span style="float: right;">
          <%= link_to "Remove gift", list_gift_path(@list, gift), method: :delete, remote: true, data: { confirm: 'Are you sure you wish to delete this gift?' } %>
        </span>
        <% end %>
        <h6 class="card-subtitle mb-2 text-muted">Notes: <%= gift.notes %></h6>
        <a href="<%= gift.url %>"><%= gift.url %></a>
      </span>

      <span class="card-footer">
        <i>
          added <%= time_ago_in_words(gift.created_at) %> ago
        </i>
      </span>
    </div>
    <br>
  <% end %>

app/views/gifts/new.html.erb
<h1 class="text-center" style="font-weight: lighter;"> New Gift </h1>

<%= render "form", gift: @gift %>
<div class="card mx-auto text-center px-4 pt-4 pb-3 mt-5" style="width: 375px;">
    <%= link_to 'Back to Lists', lists_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllIWantFor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
    <nav class="navbar">
      <a href="/lists" class="navbar-brand"><img src="<%=asset_path('all-i-want-for.png')%>" alt="AllIWantFor" height="200" width="200"></a>
      <div>
        <% if current_user %>
        <span>
          Welcome, <%= current_user.username %>
          <a href="/lists" class="btn btn-primary ml-4 px-2 py-1">Lists</a>
          <a href="/lists/new" class="btn btn-success ml-4 px-2 py-1">New List</a>
          <%= link_to 'Sign Out', logout_path, class: "btn btn-danger ml-4" %>
        </span>
      <% else %>
        <%= link_to 'Sign Up', new_user_path, class: "btn btn-success mr-4" %>
        <%= link_to 'Sign In', new_session_path, class: "btn btn-primary" %>
      <% end %>
      </div>
    </nav>

    <% flash.each do |type, msg| %>
      <div class="alert alert-info text-center mx-auto" role="alert" style="width: 98.38%;">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="card mx-auto text-center px-4 pt-4 pb-3 mt-5" style="width: 375px;">
  <%= form_for @list do |f| %>
    <%= f.label :name, 'List name' %>
    <%= f.text_field :name, class: "form-control mb-3" %>
    <%= f.label :event_date, 'Event date' %>
    <%= f.date_field :event_date, class: "form-control mb-3" %>
    <%= f.submit 'Submit', class: "btn btn-success" %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<h1 class="text-center" style="font-weight: lighter;"> Edit list details </h1>

<%= render "form", list: @list %>

app/views/lists/index.html.erb
<h1 class="text-center" style="font-weight: lighter;">Gift Lists</h1>
<% @lists.reverse.each do |list| %>
  <div class="card mb-5 mx-auto" style="width: 80%;">
    <span class="card-header">
      <b>
        <%= list.user.username.capitalize %>
      </b>
      <i>
        created
        <%= time_ago_in_words(list.created_at) %> ago
      </i>
      <% if list.user == current_user %>
      <span style="float: right;">
        <%= link_to "Edit list", edit_list_path(list), class: "btn btn-primary" %>
        <%= link_to "Delete list", list_path(list), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?"} %>
      </span>
      <% end %>
    </span>
    <span class="d-inline-flex">
      <p class="text-justify m-2"><%= list.name %> - event date <%= list.event_date.strftime("%d/%m/%Y") %></p>
    </span>
    <span class="card-footer">
      <% if list.user == current_user %>
        <%= link_to 'Add Gift', new_list_gift_path(list), class: "btn btn-primary" %>
      <% end %>
        <%= link_to 'View List', list_path(list), class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/lists/new.html.erb
<h1 class="text-center" style="font-weight: lighter;"> New list </h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<h1 class="text-center" style="font-weight: lighter;"><%= @list.user.username.capitalize %>'s List</h1>
<div class="card my-5 mx-auto" style="width: 80%;" id="list-container">
  <span class="card-header">
    <b>
    <%= @list.name %> - <%= @list.event_date.strftime("%d/%m/%Y") %>
    </b>

    <% if @list.user == current_user %>
    <span style="float: right;">
        <%= link_to 'Add Gift', new_list_gift_path(@list), class: "btn btn-primary" %>
        <%= link_to "Edit List", edit_list_path(@list), class: "btn btn-primary" %>
        <%= link_to "Delete List", list_path(@list), class: "btn btn-primary", method: :delete, data: { confirm: "Are you sure?"} %>
    </span>
    <% end %>
  </span>
  <span class="d-inline-flex">
    <p></p>
  </span>

  <br>
  <div id="gifts-container">
    <%= render 'gifts/index' %>
  </div>
</div>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger text-center mx-auto" role="alert">
        <%= msg %>
      </div>
    <% end %>
  <% end %>

  <div class="card mx-auto text-left px-4 pt-4 pb-3 mt-5" style="width: 375px;">
    <h3 class="card-title mb-3 text-center" style="font-weight: lighter;">Register with All I Want For</h3>
    <%= f.text_field :username, placeholder: 'username', class: "form-control mb-3" %>
    <%= f.text_field :email, placeholder: 'email', class: "form-control mb-3" %>
    <%= f.password_field :password, placeholder: 'password', class: "form-control mb-3" %>
    <%= f.password_field :password_confirmation, placeholder: 'password confirmation', class: "form-control mb-3" %>
    <%= f.date_field :birthdate, placeholder: 'Date of Birth', class: "form-control mb-3" %>
    <%= f.submit 'Sign Up', class: "btn btn-success" %>
  <% end %>
</div>

app/views/users/welcome.html.erb
<h1><%= "Welcome, #{@user}!" %></h1>

app/views/welcome/index.html.erb
<div class="container-sm">
    <h3 class="text-center">Welcome to 'All I Want For'</h3>
    <br>
    <p class="text-center">A site to create and share gift lists</p>
    <div style="text-align: center"><a href="/users/new" >Sign up</a> to be able to create your own gift lists.</div>
    <div style="text-align: center">Or <a href="lists">browse all lists</a> on the site.</div>
</div>

<%= flash[:notice] %>